variables:
    GODOT_VERSION: 3.2.2
    GODOT_RELEASE: stable
    ANDROID_HOME: /root/android-sdk
    ANDROID_NDK_VERSION: 17.2.4988734
    ANDROID_NDK_HOME: /root/android-sdk/cmdline-tools/ndk/17.2.4988734
    ANDROID_BUILD_TOOLS_VERSION: 29.0.3
    ANDROID_PLATFORM_VERSION: 29
    CMAKE_VERSION: 3.6.4111459

image: bitnami/minideb:stretch

stages:
    - build

godot:
    stage: build
    script:
        - chmod +x ./install_build_dependencies.sh
        - ./install_build_dependencies.sh
        - chmod +x ./compile_godot.sh
        - ./compile_godot.sh
        - chmod +x ./install_sdk_ndk.sh
        - ./install_sdk_ndk.sh
        - chmod +x ./compile_android_templates.sh
        - ./compile_android_templates.sh
    artifacts:
        name: godot_with_android_templates
        paths:
            - godot-${GODOT_VERSION}-${GODOT_RELEASE}/bin
